version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.12.1
    - 1.0.0
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 2.32.10
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.2.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 4.1.0
  - dependency-name: gatsby-plugin-nprogress
    versions:
    - 3.1.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
